#!/usr/bin/with-contenv bash

cat <<__EOF__ | tee -a /root/.bashrc /config/.bashrc

#
# Anaconda / Sfepy mods
#
export PATH=/opt/conda/bin:${PATH}
. /etc/profile.d/conda.sh
conda activate base
#
__EOF__

# Add conda-forge channel
conda config --system --add channels conda-forge
#